# -*- coding: utf-8 -*-
import random


def get_lastname():
    lastname = [
        'Almeida',
        'Amorim',
        'Abbud',
        'Abreu',
        'Agrizi',
        'Airoso',
        'Albani',
        'Albino',
        'Alfarenga',
        'Álvares',
        'Amaral',
        'Ambrozin',
        'Anchesqui',
        'Andreão',
        'Anna',
        'Antunes',
        'Appolinario',
        'Arpini',
        'Assú',
        'Augustsdatter',
        'Barnett',
        'Butler',
        'Baiense',
        'Baldotto',
        'Bandeira',
        'Barbato',
        'Barnabe',
        'Barrazzuol',
        'Barroso',
        'Basso',
        'Bastos',
        'Battistela',
        'Bedard',
        'Bellon',
        'Bena?',
        'Benica',
        'Bergami',
        'Bernadot',
        'Bernardini',
        'Bertone',
        'Betine',
        'Bianche',
        'Bicudo',
        'Bitelli',
        'Boarin',
        'Boldrin',
        'Bonadiman',
        'Bonot',
        'Borsoi',
        'Bortoloti',
        'Botacin',
        'Botti',
        'Bracesque',
        'Bragatto',
        'Branch',
        'Bravim',
        'Breda',
        'Brezininiski',
        'Brino',
        'Brito',
        'Brum',
        'Bruno',
        'Brusque',
        'Buoro',
        'Buzatto',
        'Calmon',
        'Constâncio',
        'Calabreza',
        'Caldeira',
        'Califfe',
        'Calliman',
        'Camargo',
        'Camilete',
        'Camporês',
        'Campos',
        'Canceglieri',
        'Cansian',
        'Caprini',
        'Cardosa',
        'Carlesso',
        'Carneiro',
        'Carrasco',
        'Carvalho',
        'Casaro',
        'Castro',
        'Cavalcanti',
        'Ceccon',
        'Celot',
        'Cerqueira',
        'Cesconetto',
        'Cheibub',
        'Chies',
        'Christiansdatter',
        'Cipriano',
        'Cocco',
        'Côgo',
        'Colli',
        'Colombi',
        'Conciani',
        'Contarini',
        'Corocher',
        'Correya',
        'Costa Longa',
        'Cota',
        'Cremasco',
        'Cruz',
        'Curitiba',
        'de Candia',
        'de Moraes',
        'dos Santos',
        'da Camara',
        'da Cunha',
        'da Polloni',
        'da Silveira',
        'Dalcin',
        'Dalla Marta',
        'Daltro',
        'Dancy',
        'Dardengo',
        'Dassié',
        'de Abreu',
        'de Albernas',
        'de Alvarenga',
        'De Angeli, Neto',
        'de Ayrosa',
        'de Azevedo',
        'de Barros',
        'de Carvalho',
        'de Deus',
        'de Freitas',
        'de Jesus',
        'de Lima',
        'de Martins',
        'de Melo',
        'de Moura',
        'de Oliviera',
        'De Paoli',
        'de Sa',
        'De Stefani',
        'Debona',
        'Delarmelina',
        'Della Libera',
        'Demoni',
        'Destéfani',
        'Esteve',
        'Eckharger',
        'Entrinula',
        'Espino',
        'Ferreia',
        'Francia',
        'Faccina',
        'Facundtto',
        'Falque',
        'Faria',
        'Fassar',
        'Fazolli',
        'Ferlino',
        'Ferrão',
        'Fileti',
        'Fiorav',
        'Fiorinto',
        'Firesecio',
        'Gaiotto',
        'Gardiman',
        'Gasparini',
        'Gava',
        'Gazola',
        'Geacomelli',
        'Giuduce',
        'Gibbo',
        'Gonçalves',
        'Grassi',
        'Grillo',
        'Gredes',
        'Guidini',
        'Hanrichsdt.',
        'Herman',
        'Heracio',
        'Hodiv',
        'Joensdatter',
        'Johansen',
        'Josefa',
        'Justi',
        'Lacerda',
        'Lago',
        'Lanes',
        'Larsen',
        'Leal',
        'Loredetto',
        'Lorencini',
        'Loreto',
        'Maciel',
        'Mafra',
        'Magro',
        'Majeski',
        'Malvezzi',
        'Marcarini',
        'Marcon',
        'Maria',
        'Marin',
        'Mario',
        'Maróquio',
        'Marquette',
        'Mascarello',
        'Massardi',
        'Mateus',
        'Mathiélo',
        'Matioz',
        'Mauro',
        'MaCune',
        'Menegardo',
        'Menezes',
        'Merotto',
        'Melaneze',
        'Minatel',
        'Minetti',
        'Miranda',
        'Monteiro',
        'Morais',
        'Morgan',
        'Mortensdatter',
        'Mosquini',
        'Moura, Filho',
        'Moscareli',
        'Napoleão',
        'Narg',
        'Néves',
        'Nielsdatter',
        'Nielson',
        'Novais',
        'Ocausdatter',
        'Oliveira',
        'Olhas',
        'Ormo',
        'Ortitty',
        'Possebon',
        'Pagani',
        'Pagotto',
        'Palù',
        'Panhoca',
        'Parente',
        'Partelli',
        'Pase',
        'Pasti',
        'Paulo',
        'Pazetto',
        'Pedersen',
        'Pegovaro',
        'Peppelenbos',
        'Perdoná',
        'Perez',
        'Perizin',
        'Perreyra',
        'Pessanha',
        'Peterli',
        'Piana',
        'Pianessola',
        'Pianezzola',
        'Piassi',
        'Pilati',
        'Pinheiro',
        'Pires',
        'Pizzeta',
        'Plotegher',
        'Polinini',
        'Pontes',
        'Pozinni',
        'Prates',
        'Premoli',
        'Puppim',
        'Romanini',
        'Ragazzo',
        'Rangel',
        'Rasmussen',
        'Réboli',
        'Reinehr',
        'Resolen',
        'Ricarte',
        'Rigone',
        'Rios',
        'Rochite',
        'Romanholi',
        'Ronqueti',
        'Rosas',
        'Rossi',
        'Rozario',
        'Rugero',
        'Selvatici',
        'Saiter',
        'Salomão',
        'Sanavia',
        'Sangali',
        'Santori',
        'Sartori',
        'Scanferla',
        'Schael',
        'Schulthais',
        'Scott',
        'Seguro',
        'Serafim',
        'Sgulmaro',
        'Siciliano',
        'Siqueira',
        'Sobrinho',
        'Solda',
        'Sossai detto Pegorer',
        'Stefani',
        'Stradiotto',
        'Svendsdatter',
        'Teves',
        'Tassinari',
        'Tedesco',
        'Teles',
        'Thirine',
        'Tomasi',
        'Ton',
        'Tonoli',
        'Toste',
        'Tozi',
        'Trabach',
        'Tres',
        'Tronerin',
        'Uliana',
        'Vasconcelos',
        'Valani',
        'Valiatti',
        'Varella',
        'Vekar',
        'Venturini',
        'Vescovi',
        'Vianna',
        'Viebrantz',
        'Villares',
        'Vinco',
        'Volponi',
        'Wainer',
        'Warner',
        'Werner',
        'Zardo',
        'Zambon',
        'Zampirollo',
        'Zancanela',
        'Zanelato',
        'Zanon',
        'Zavarize',
        'Zocatelli',
        'Zucatelli',
    ]
    name = random.choice(lastname)
    return name
